### ISSUE TITLE
v0.1.3 requires additional rbac permissions

### ISSUE THREAD

**Issue by bentrombley** [zalando-incubator/kube-metrics-adapter#142]
We just upgraded from 0.1.0 to 0.1.3 and started seeing errors in our logs like: 
```E0413 20:07:05.845509       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:custom-metrics-apiserver" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

I'm not sure what changed, but it seems something is looking up `ConfigMap` in apigroup `""`. This change fixed it for us:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-metrics-resource-collector
rules:
...
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
```

## Expected Behavior
There should be no errors/warnings in the logs. 

## Actual Behavior
See above logs. This caused the HorizontalPodAutoscalers to fail.

## Steps to Reproduce the Problem

  1. Create installation following the configuration in the `docs/` folder.
  1. Use either AWS SQS queue or HTTP collector (following docs in the README)
  1. Look at the logs on the `kube-metrics-adapter` pod.

## Specifications

  - Version: Kubernetes v.15.17

**Comment by bentrombley** [comment]
Sorry, I'd submit a pull request, but that would require a lengthy approval process from my employer.

**Comment by mikkeloscar** [comment]
Hi @bentrombley there should be a default role in the cluster called: `extension-apiserver-authentication-reader` This we bind to here: https://github.com/zalando-incubator/kube-metrics-adapter/blob/97ec13d010bd58af766289932381e957ab47de30/docs/rbac.yaml#L116

Does your cluster not have this role as default? From what I can see it should also be in v1.15.7

**Comment by zsoltbaloghmaden** [comment]
I experienced same issue after I added that line working perfectly.

**Comment by RRAlex** [comment]
Same here, adding this section to the `clusterrole/custom-metrics-resource-collector` made the metrics work on my k8s (1.18.3).
What confuses me is that I installed a cluster a month ago (1.18.2), without that part, and it works... :thinking: 
```
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
```
