### ISSUE TITLE
SQS hpa throwing region error

### ISSUE THREAD

**Issue by pc-rnukala1** [zalando-incubator/kube-metrics-adapter#154]
## Expected Behavior

HPA should get the given sqs queue metric.

## Actual Behavior

`time="2020-05-19T07:28:31Z" level=info msg="Event(v1.ObjectReference{Kind:\"HorizontalPodAutoscaler\", Namespace:\"test-app\", Name:\"test-hpa\", UID:\"916f0d14-999d-11ea-9292-0aead91950b0\", APIVersion:\"autoscaling/v2beta2\", ResourceVersion:\"88872595\", FieldPath:\"\"}): type: 'Warning' reason: 'CreateNewMetricsCollector' Failed to create new metrics collector: the metric region: us-west-2 is not configured"`

Here is my hpa config: 

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: sqs-queue-length
        selector:
          matchLabels:
            queue-name: TEST_QUEUE
            region: us-west-2
      target:
        averageValue: "30"
        type: AverageValue

```

## Specifications

  - Version: 1.14
  - Platform: centos
  - Subsystem:
