### ISSUE TITLE
non sence target value compare to the value in the prometheus 

### ISSUE THREAD

**Issue by ehsanrocket** [zalando-incubator/kube-metrics-adapter#189]
Hi all
I have set up the external metrics
from the Prometheus the query eg X shows the 34 value 
and I have set the ```AverageValue``` to 15 in hpa 
```
target:
        type: AverageValue
        averageValue: 15

```
it works correctly and for the value 34 the HPA create 3 replica 
but in kubernetes the HPA shows ```10334m/15```
how 34 is being converted to ```10334m``` ?

this is my full HPA : 
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: test
  name: XX
  annotations:
prometheus.default.svc.cluster.local:9090
    metric-config.external.prometheus-query.prometheus/X: |
      X
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: prometheus-query
        selector:
          matchLabels:
            query-name: X
      target:
        type: AverageValue
        averageValue: 15

```
