### ISSUE TITLE
Possible to write HPA using nested prometheus metric ?

### ISSUE THREAD

**Issue by karthikborkar** [zalando-incubator/kube-metrics-adapter#20]
## Expected Behavior
- prometheus is setup and recording metrics from collectd using collectd to Prometheus and can be queried Prometheus  like this which gives 

`curl prometheus.monitoring.svc:9090/api/v1/query?query="collectd_statsd_derive_total"`

>{
	"status": "success",
	"data": {
		"resultType": "vector",
		"result": [{
			"metric": {
				"__name__": "collectd_statsd_derive_total",
				"exported_instance": "collectd-statsd-6f5475dd46-92fx4",
				"instance": "collectd-statsd.monitoring.svc:9103",
				"job": "collect-statsd",
				"statsd": "prometheus_target_kbasync_lenh_sec"
			},
			"value": [1544343252.741, "6"]
		}, {
			"metric": {
				"__name__": "collectd_statsd_derive_total",
				"exported_instance": "collectd-statsd-6f5475dd46-92fx4",
				"instance": "collectd-statsd.monitoring.svc:9103",
				"job": "collect-statsd",
				"statsd": "targetkb_kbasync_lenh_sec"
			},
			"value": [1544343252.741, "3"]
		}, {
			"metric": {
				"__name__": "collectd_statsd_derive_total",
				"exported_instance": "collectd-statsd-6f5475dd46-92fx4",
				"instance": "collectd-statsd.monitoring.svc:9103",
				"job": "collect-statsd",
				"statsd": "targetkb_kbasync_lenh_sec_g"
			},
			"value": [1544343252.741, "240"]
		}, {
			"metric": {
				"__name__": "collectd_statsd_derive_total",
				"exported_instance": "collectd-statsd-6f5475dd46-92fx4",
				"instance": "collectd-statsd.monitoring.svc:9103",
				"job": "collect-statsd",
				"statsd": "targetkb_kbasync_lenh_sec_gg"
			},
			"value": [1544343252.741, "3"]
		}, {
			"metric": {
				"__name__": "collectd_statsd_derive_total",
				"exported_instance": "collectd-statsd-6f5475dd46-92fx4",
				"instance": "collectd-statsd.monitoring.svc:9103",
				"job": "collect-statsd",
				"statsd": "targetkb_kbasync_lenh_sec_ggg"
			},
			"value": [1544343252.741, "3"]
		}]
	}
}

My metric name is stored in key  `statsd` key  in above response returned by prometheus 
eg :"statsd": "targetkb_kbasync_lenh_sec_ggg"

i want to write an HPA using metric name from key `statsd`

**Comment by karthikborkar** [comment]
I have tried this:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: custom-metrics-consumer
  namespace: default
  labels:
    application: custom-metrics-consumer
  annotations:
    # metric-config.<metricType>.<metricName>.<collectorName>/<configKey>
    metric-config.object.prometheus-target-kbasync-lenh-sec.prometheus/query: |
      scalar(sum(rate(collectd_statsd_derive_total{statsd="prometheus_target_kbasync_lenh_sec"}[1m])))
    metric-config.object.prometheus-target-kbasync-lenh-sec.prometheus/per-replica: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: custom-metrics-consumer
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: prometheus-target-kbasync-lenh-sec
      targetAverageValue: 1
```

My prometheus query is correct :

> curl -g prometheus.monitoring.svc:9090/api/v1/query?query="scalar(sum(rate(collectd_statsd_derive_total{statsd='prometheus_target_kbasync_lenh_sec'}[5m])))"
{"status":"success","data":{"resultType":"scalar","result":[1544377450.443,"0.008333333333333333"]}}

>
