### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Typraeurion** [zalando-incubator/kube-metrics-adapter#216]
We had the kube-metrics-adapter running when we initially set up our K8s cluster earlier this year (in Amazon EKS).  However after upgrading the cluster to 1.18 today I checked the kube-system pods and noticed that the adapter had been crashing.
```
NAME                                      READY   STATUS             RESTARTS   AGE
alb-ingress-controller-6679fbb9b4-z4d2h   1/1     Running            0          69m
aws-node-b9pld                            1/1     Running            0          81m
coredns-66bc8b7b7b-c4qzl                  1/1     Running            0          77m
coredns-66bc8b7b7b-ptbw4                  1/1     Running            0          69m
kube-metrics-adapter-cd6b4c9b6-pnzh5      0/1     CrashLoopBackOff   19         77m
kube-proxy-8xl48                          1/1     Running            0          81m
metrics-server-7f5bdbbb44-md4zl           1/1     Running            0          20s
```

I compared our YAML configs to the current files under docs/ and don’t see any changes.  The log output from the pod shows a panic right after generating its self-signed certificate:
```
I1026 20:05:10.939037       1 serving.go:307] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a4c89c]

goroutine 1 [running]:
github.com/zalando-incubator/kube-metrics-adapter/pkg/server.AdapterServerOptions.RunCustomMetricsAdapterServer(0xc0006e2a80, 0x0, 0x0, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/server/start.go:129 +0x11c
github.com/zalando-incubator/kube-metrics-adapter/pkg/server.NewCommandStartAdapterServer.func1(0xc00048bb80, 0x2e18ba8, 0x0, 0x0, 0x0, 0x0)
	/workspace/pkg/server/start.go:69 +0x85
github.com/spf13/cobra.(*Command).execute(0xc00048bb80, 0xc0001041b0, 0x0, 0x0, 0xc00048bb80, 0xc0001041b0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00048bb80, 0xc00012c120, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	/workspace/main.go:40 +0xb8
```

## Expected Behavior
Pod remains in “Running” state

## Actual Behavior
Pod continually cycles between “Running”, “Error”, and “CrashLoopBackOff” states

## Steps to Reproduce the Problem
Installed rbac.yaml, custom-metrics-apiservice.yaml, external-metrics-apiservice.yaml, and service.yaml as-is.  Installed a slightly modified deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-metrics-adapter
  namespace: kube-system
  labels:
    application: kube-metrics-adapter
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-metrics-adapter
  template:
    metadata:
      labels:
        application: kube-metrics-adapter
        version: latest
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: kube-metrics-adapter
        image: registry.opensource.zalan.do/teapot/kube-metrics-adapter:latest
        args:
        # - --v=9
        # - --aws-external-metrics
        env:
        - name: AWS_REGION
          value: us-east-2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
(all annotations and args have been removed, and “eu-central-1” replaced with “us-east-2”.)

## Specifications

  - Version: registry.opensource.zalan.do/teapot/kube-metrics-adapter:latest
  - Platform: Kubernetes 1.18.8
  - Subsystem: EKS-Optimized AMI 1.18.8-20201007
