### ISSUE TITLE
Several HPAs with equal query name but not equal query body

### ISSUE THREAD

**Issue by ASKozienko** [zalando-incubator/kube-metrics-adapter#225]
For example we have 2 HPAs but query name is same for both of them `metric-config.external.prometheus-query.prometheus/query`
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa1
  annotations:
    metric-config.external.prometheus-query.prometheus/query:  QUERY1
```

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa2
  annotations:
    metric-config.external.prometheus-query.prometheus/query:  QUERY2
```
How does it work? Each HPA use own defined query or QUERY1 will be overwritten with QUERY2?
