### ISSUE TITLE
Failed to create new metrics collector

### ISSUE THREAD

**Issue by ricgatti** [zalando-incubator/kube-metrics-adapter#227]
## Expected Behavior
`kube-metrics-adapter` should be able to create a metrics collector based on the example in the readme.

## Actual Behavior

```
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
```

And in the log of kube-metrics-adapter pod
```
time="2020-11-16T13:59:44Z" level=info msg="Found 1 new/updated HPA(s)" provider=hpa
time="2020-11-16T13:59:44Z" level=info msg="Event(v1.ObjectReference{Kind:\"HorizontalPodAutoscaler\", Namespace:\"default\", Name:\"backoffice-hpa\", UID:\"0361deea-921b-4c7b-811f-160cf30312a9\", APIVersion:\"autoscaling/v2beta2\", ResourceVersion:\"51571526\", FieldPath:\"\"}): type: 'Warning' reason: 'CreateNewMetricsCollector' Failed to create new metrics collector: no plugin found for {External {nginx-connections-active &LabelSelector{MatchLabels:map[string]string{type: prometheus,},MatchExpressions:[]LabelSelectorRequirement{},}}}"
```

## Steps to Reproduce the Problem

  1. Using the manifests with some updation of config parameters in (https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/cluster/manifests/kube-metrics-adapter)
  2. Create HPA
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backoffice-hpa
  annotations:
    metric-config.external.nginx-connections-active.prometheus/query: |
      nginx_connections_active{service="backoffice-srv"}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backoffice-dpy
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: External
      external:
        metric:
          name: nginx-connections-active
          selector:
            matchLabels:
              type: prometheus
        target:
          type: AverageValue
          averageValue: "10"
```

## Specifications

  - Version: v0.1.9
  - Platform: EKS
  - Subsystem:

**Comment by mikkeloscar** [comment]
@ricgatti Thanks for reporting this. There are two reasons it doesn't work:

* The new style of configuring the HPA which is documented in the README is not yet released in a version and thus does not work with `v0.1.9`
* I found a bug in the prometheus metric type setup, which is addresses in #228 

So to resolve the issue you can either wait for #228 to be merged and use the latest image, or you can use the old style setup which would mean your HPA should look like this:

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backoffice-hpa-legacy
  annotations:
    metric-config.external.prometheus-query.prometheus/nginx-connections-active: |
      nginx_connections_active{service="backoffice-srv"}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backoffice-dpy
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: External
      external:
        metric:
          name: prometheus-query
          selector:
            matchLabels:
              query-name: nginx-connections-active
        target:
          type: AverageValue
          averageValue: "10"
```

Sorry for the confusion right now, we're right in a transition to a new improved format but have yet to release a version which supports it.
