### ISSUE TITLE
HPA error : no metrics returned from external metrics API

### ISSUE THREAD

**Issue by knkarthik** [zalando-incubator/kube-metrics-adapter#237]
I've installed `kube-metrics-adapter` from [manifests from](https://github.com/zalando-incubator/kube-metrics-adapter/tree/master/docs) `docs`. I'm trying to use this to expose metrics provided by [gitlab-runner](https://docs.gitlab.com/runner/monitoring/).

From Prometheus:
```
gitlab_runner_jobs{executor_stage="prepare",instance="172.17.0.9:9252",job="kubernetes-pods",namespace="default",pod="gitlab-runner-gitlab-runner-56cf46ddf-b7lv6",runner="AnZYK5xA",stage="step_script",state="running"}
```

Logs from `kube-metrics-adapter`:

```
time="2020-12-07T19:29:27Z" level=info msg="Looking for HPAs" provider=hpa                                                                │
│ time="2020-12-07T19:29:27Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa                                                      │
│ time="2020-12-07T19:29:57Z" level=info msg="Looking for HPAs" provider=hpa                                                                │
│ time="2020-12-07T19:29:57Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa                                                      │
│ time="2020-12-07T19:30:27Z" level=info msg="Collected 1 new metric(s)" provider=hpa                                                       │
│ time="2020-12-07T19:30:27Z" level=info msg="Collected new external metric 'processed-events-per-second' (1) [type=prometheus]" provider=hpa│
```
and raw query:
```
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/" | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "processed-events-per-second",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

but HPA can't find this:

```
kubectl describe hpa
Name:                                                    gitlab-hpa
Namespace:                                               default
Labels:                                                  <none>
Annotations:                                             metric-config.external.processed-events-per-second.prometheus/prometheus-server: http://prometheus.monitoring.svc.cluster.local:9090
                                                         metric-config.external.processed-events-per-second.prometheus/query: sum(gitlab_runner_jobs{state="running"})
CreationTimestamp:                                       Mon, 07 Dec 2020 14:16:00 -0500
Reference:                                               Deployment/gitlab-runner-gitlab-runner
Metrics:                                                 ( current / target )
  "processed-events-per-second" (target average value):  1 / 1
Min replicas:                                            1
Max replicas:                                            3
Deployment pods:                                         1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric processed-events-per-second(&LabelSelector{MatchLabels:map[string]string{type: prometheus,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  CreateNewMetricsCollector     13m (x9 over 17m)  kube-metrics-adapter       Failed to create new metrics collector: query or query name not specified on metric
  Warning  FailedGetExternalMetric       13m                horizontal-pod-autoscaler  unable to get external metric default/processed-events-per-second/&LabelSelector{MatchLabels:map[string]string{type: prometheus,},MatchExpressions:[]LabelSelectorRequirement{},}: no metrics returned from external metrics API
  Warning  FailedComputeMetricsReplicas  13m                horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get processed-events-per-second external metric: unable to get external metric default/processed-events-per-second/&LabelSelector{MatchLabels:map[string]string{type: prometheus,},MatchExpressions:[]LabelSelectorRequirement{},}: no metrics returned from external metrics API
```

**Comment by mikkeloscar** [comment]
What does your HPA look like?

**Comment by knkarthik** [comment]
@mikkeloscar 
> What does your HPA look like?

```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: gitlab-hpa
  annotations:
    metric-config.external.processed-events-per-second.prometheus/prometheus-server: http://prometheus.monitoring.svc.cluster.local:9090
    metric-config.external.processed-events-per-second.prometheus/query: | 
        sum(gitlab_runner_jobs{state="running"})
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gitlab-runner-gitlab-runner
  metrics:
  - type: External
    external:
      metric:
        name: processed-events-per-second
        selector:
          matchLabels:
             type: prometheus
      target:
        type: AverageValue
        averageValue: "1"

```
