### ISSUE TITLE
HPA error, GKE unable to read custom metric requests-per-second.

### ISSUE THREAD

**Issue by vineel-concat** [zalando-incubator/kube-metrics-adapter#254]
I am trying to create a custom metric based auto-scaling based on requests per second on GKE.

Installed the kube-metrics-adapter by applying https://github.com/zalando-incubator/kube-metrics-adapter/tree/master/docs yaml files. 

On GKE cluster, enabled istio and installed Prometheus using 
```
kubectl -n istio-system apply -f \
https://storage.googleapis.com/gke-release/istio/release/1.0.6-gke.3/patches/install-prometheus.yaml
```

After installing, created an HPA based on the example provided in the readme

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-app-hpa
  annotations:
    # metric-config.<metricType>.<metricName>.<collectorType>/<configKey>
    metric-config.pods.requests-per-second.json-path/json-key: "$.http_server.rps"
    metric-config.pods.requests-per-second.json-path/path: /metrics
    metric-config.pods.requests-per-second.json-path/port: "9090"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      metric:
        name: requests-per-second
      target:
        averageValue: 10
        type: AverageValue
```

Exposed application using load balancer by port forwarding from port 80 to container 8080 port. 

In cloud console, it shows an error that "HPA cannot read metric value"

Checked the error log by running
`kubectl -n kube-system logs deployment/kube-metrics-adapter
`
Seeing the following error:

```
level=error msg="Failed to get metrics from pod 'test/hello-app-69fd99d7c8-52qfg': Get http://10.0.0.26:9090/metrics: read tcp 10.0.0.22:42130->10.0.0.26:9090: read: co
nnection reset by peer" Collector=Pod
```

Thanks
