### ISSUE TITLE
external metrics error

### ISSUE THREAD

**Issue by dudicoco** [zalando-incubator/kube-metrics-adapter#257]
Hi,

We've upgraded from v0.0.5 to v0.1.9 and changed the hpa spec to the following:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  annotations:
    metric-config.external.http-requests-total.prometheus/interval: 30s
    metric-config.external.http-requests-total.prometheus/query: |
      http_requests_total{release="my-deploy"}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metric:
        name: http-requests-total
        selector:
          matchLabels:
            type: prometheus
      target:
        type: AverageValue
        averageValue: 1
```

We are seeing the following in the logs:
```
time="2021-01-21T15:23:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"HorizontalPodAutoscaler\", Namespace:\"mynamespace\", Name:\"my-deploy\", UID:\"1046055a-9df7-4286-bc27-f3b74713a5db\", APIVersion:\"autoscaling/v2beta2\", ResourceVersion:\"124405892\", FieldPath:\"\"}): type: 'Warning' reason: 'CreateNewMetricsCollector' Failed to create new metrics collector: no plugin found for {External {http-requests-total &LabelSelector{MatchLabels:map[string]string{type: prometheus,},MatchExpressions:[]LabelSelectorRequirement{},}}}"
```

When using the `latest` image tag the error is gone.

In addition, it seems that kube-metrics-adapter is still able to collect metrics from hpas in API version autoscaling/v2beta1 , although this API is not supported in the new version.
