### ISSUE TITLE
CreateNewMetricsCollector : Failed to create new metrics collector

### ISSUE THREAD

**Issue by humayunjamal** [zalando-incubator/kube-metrics-adapter#30]
## Expected Behavior
external and custom metrics api should give  some output but there is none 

## Actual Behavior

 kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
## Steps to Reproduce the Problem

  1. Using the manifests with some updation of config parameters in (https://github.com/zalando-incubator/kubernetes-on-aws/tree/dev/cluster/manifests/kube-metrics-adapter), I am able to run the kube-metrics-apdapter but the logs of the container constantly show the below warnings 

```
time="2019-01-22T10:32:24Z" level=info msg="Looking for HPAs" provider=hpa
time="2019-01-22T10:32:24Z" level=info msg="Found 1 new/updated HPA(s)" provider=hpa
time="2019-01-22T10:32:24Z" level=info msg="Event(v1.ObjectReference{Kind:\"HorizontalPodAutoscaler\", Namespace:\"default\", Name:\"myservice-k8\", UID:\"ba31da13-1e10-11e9-a841-06f3d10b141c\", APIVersion:\"autoscaling/v2beta1\", ResourceVersion:\"36437\", FieldPath:\"\"}): type: 'Warning' reason: 'CreateNewMetricsCollector' Failed to create new metrics collector: format '' not supported"
```
Can not find any documentation or examples explaining what is expected here ? 

Using the example I am able to successfully run kube-ingress-aws-controller  in (https://github.com/zalando-incubator/kube-ingress-aws-controller/tree/master/deploy)

And my prometheus stack detects the skipper metrics and I can see in my promethues graphs the values such as 

```
skipper_response_duration_seconds_sum{application="skipper",code="200",component="ingress",controller_revision_hash="1183544327",instance="172.20.4.24:9911",job="kubernetes-pods",kubernetes_namespace="kube-system",kubernetes_pod_name="skipper-ingress-mpm6g",method="GET",pod_template_generation="3",route="kube_default__myservice_k8__myservice_k8_stag_mydomain_com____myservice_k8_0__lb_group"}
```

Now I am expecting/assuming that when I run kube-metrics-adapter with configurations mentioned above , I should be able to see some metrics under api `/apis/external.metrics.k8s.io/v1beta1` or /apis/custom.metrics.k8s.io/v1beta1
but its empty . 

Remember myservice is NOT running any metrics exporter. 

## Specifications

  - Version:1.11
  - Platform: EKS
  - Subsystem:

**Comment by humayunjamal** [comment]
@szuecs your help/guidance here will be much appreciated :)

**Comment by humayunjamal** [comment]
@mikkeloscar  the hpa setting for myservice is 

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myservice-k8
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: myservice-k8
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 1G
  - type: Pods
    pods:
      metricName: cpu_system
      targetAverageValue: 20m
```
