### ISSUE TITLE
Failed to create new metrics collector (external metrics)

### ISSUE THREAD

**Issue by paul-benetis** [zalando-incubator/kube-metrics-adapter#331]
## Expected Behavior
The adapter should retrieve a json object from the endpoint and use the specified value for autoscaling.

## Actual Behavior
HPA returns this error:
`Failed to create new metrics collector: identifier is not specified as a label for metric queue-length`
Note: Internal metrics work properly.

## Steps to Reproduce the Problem

Installed the adapter with the following settings enabled:
`enableCustomMetricsApi: true`
`enableExternalMetricsApi: true`

HPA config:

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: custom-metrics-consumer
  namespace: default
  labels:
    application: custom-metrics-consumer
  annotations:
    # metric-config.<metricType>.<metricName>.<collectorType>/<configKey>
    metric-config.external.queue-length.json-path/json-key: "$.[99].id" # returns value of 100
    metric-config.external.queue-length.json-path/endpoint: "https://jsonplaceholder.typicode.com/posts"
    metric-config.external.queue-length.json-path/interval: "5s"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: custom-metrics-consumer
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: queue-length
        selector:
          matchLabels:
            type: json-path
      target:
        averageValue: 50
        type: AverageValue
```

## Specifications

  - Version: 1.20
  - Platform: EKS
