### ISSUE TITLE
Array return values do not work with json-path

### ISSUE THREAD

**Issue by fluxx-sleblanc** [zalando-incubator/kube-metrics-adapter#372]
## Expected Behavior
I attempted to use the Pod collector to collect Puma metrics using json-key: `$.worker_status.[*].last_status.backlog` - which, in testing, returns [0,0]
I expected the aggregator function to reduce the values, as the documentation shows. 

## Actual Behavior
The message returned is "unexpected json: expected single numeric or array value"

## Steps to Reproduce the Problem

  1. Use kube-metrics-adapter 0.1.15
  2. Set up a Pods collector that returns an array of metrics

## Specifications

  - Version: 1.17
  - Platform: AWS
  - Subsystem: EKS
 

I think this may have been a bug introduced by https://github.com/zalando-incubator/kube-metrics-adapter/pull/209. 
I tried swapping to the 0.1.5 image version (just before the above PR), and the metrics are collected as expected - no error. 

I verified that ajson can correctly parse the output:

```
echo '{"started_at":"2021-10-12T00:57:33Z","workers":2,"phase":0,"booted_workers":2,"old_workers":0,"worker_status":[{"started_at":"2021-10-12T00:57:53Z","pid":218,"index":0,"phase":0,"booted":true,"last_checkin":"2021-10-12T01:03:08Z","last_status":{"backlog":0,"running":1,"pool_capacity":1,"max_threads":1,"requests_count":0}},{"started_at":"2021-10-12T00:57:53Z","pid":219,"index":1,"phase":0,"booted":true,"last_checkin":"2021-10-12T01:03:08Z","last_status":{"backlog":0,"running":1,"pool_capacity":1,"max_threads":1,"requests_count":61}}]}' | ~/go/bin/ajson "$.worker_status.[*].last_status.backlog"
[0,0]
```

Here is the HPA:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: app-cpu
  namespace: infra-test
  annotations:
    # Pod collector - collect from each pod in the deployment
    # metric-config.<metricType>.<metricName>.<collectorType>/<configKey>
    metric-config.pods.requests-in-backlog.json-path/json-key: "$.worker_status.[].last_status.backlog"
    metric-config.pods.requests-in-backlog.json-path/path: /stats
    metric-config.pods.requests-in-backlog.json-path/port: "9293"
    metric-config.pods.requests-in-backlog.json-path/scheme: "http"
    metric-config.pods.requests-in-backlog.json-path/aggregator: "avg"
    metric-config.pods.requests-in-backlog.json-path/interval: "10s" # optional
    metric-config.pods.requests-in-backlog.json-path/min-pod-ready-age: "30s" # optional
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fl-app
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Pods
      pods:
        metric:
          name: requests-in-backlog
        target:
          type: AverageValue
          averageValue: 1
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
```
