### ISSUE TITLE
unable to get metric error : using prometheus-collector

### ISSUE THREAD

**Issue by Sanjanare** [zalando-incubator/kube-metrics-adapter#38]
## Expected Behavior
I have a prometheus query that can be used for scaling, expected behavoir scale up using metric
## Actual Behavior
Error: Warning  FailedGetObjectMetric         3s (x2 over 18s)  horizontal-pod-autoscaler  unable to get metric jvm-memory-bytes-used: Service on dev event-service/unable to fetch metrics from custom metrics API: the server could not find the metric jvm-memory-bytes-used for services event-service
## Steps to Reproduce the Problem

HPA yaml file:
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: aggregation-hazelcast
  namespace: dev
  annotations:
    # metric-config.<metricType>.<metricName>.<collectorName>/<configKey>
    metric-config.object.jvm-memory-bytes-used.prometheus/query: |
      scalar((sum(jvm_memory_bytes_used{area="heap"}) ) / (sum(jvm_memory_bytes_max{area="heap"}))
    metric-config.object.jvm-memory-bytes-used.prometheus/per-replica: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hazelcast
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metricName: jvm-memory-bytes-used
      target:
        apiVersion: v1
        kind: Service
        name: event-service
      targetValue: 80Mi # this will be treated as targetAverageValue
```

## Specifications

  - Version: kops version 1.12.5
  - Platform: aws
I am I missing anything ? i provided the exact query which works in prometheus

**Comment by arjunrn** [comment]
There are several things which could go wrong. Have you configured the prometheus address correctly? What do the logs say?

**Comment by Sanjanare** [comment]
yes prometheus address is correct:- using istio prometheus.
http://prometheus.istio-system.svc.cluster.local:9090

**logs:** 
error: cannot get the logs from *v1.HorizontalPodAutoscaler: selector for *v1.HorizontalPodAutoscaler not implemented

**describe events:**

Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetObjectMetric         1s (x8 over 106s)  horizontal-pod-autoscaler  unable to get metric jvm-memory-bytes-used: Service on dev event-service/unable to fetch metrics from custom metrics API: the server could not find the metric jvm-memory-bytes-used for services event-service
  Warning  FailedComputeMetricsReplicas  1s (x8 over 106s)  horizontal-pod-autoscaler  failed to get object metric value: unable to get metric jvm-memory-bytes-used: Service on dev event-service/unable to fetch metrics from custom metrics API: the server could not find the metric jvm-memory-bytes-used for services event-service

**Comment by Sanjanare** [comment]
**Kube-metrics-adpater logs:**

time="2019-03-08T16:28:16Z" level=info msg="Adding new metrics collector: *collector.PrometheusCollector" provider=hpa
time="2019-03-08T16:28:16Z" level=info msg="Found 1 new/updated HPA(s)" provider=hpa
time="2019-03-08T16:36:17Z" level=info msg="Collected 1 new metric(s)" provider=hpa
time="2019-03-08T16:36:17Z" level=info msg="Collected new custom metric 'jvm-memory-bytes-used' (128646744) for Service dev/event-service" provider=hpa
time="2019-03-08T16:36:46Z" level=info msg="Looking for HPAs" provider=hpa
time="2019-03-08T16:36:46Z" level=info msg="Removing previously scheduled metrics collector: {hazelcast dev}" provider=hpa
time="2019-03-08T16:36:46Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa
time="2019-03-08T16:36:46Z" level=info msg="stopping collector runner..."
time="2019-03-08T16:37:16Z" level=info msg="Looking for HPAs" provider=hpa
time="2019-03-08T16:37:16Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa
time="2019-03-08T16:37:46Z" level=info msg="Looking for HPAs" provider=hpa
time="2019-03-08T16:37:46Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa
time="2019-03-08T16:38:16Z" level=info msg="Looking for HPAs" provider=hpa
time="2019-03-08T16:38:16Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa
time="2019-03-08T16:38:46Z" level=info msg="Looking for HPAs" provider=hpa
time="2019-03-08T16:38:46Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa
time="2019-03-08T16:39:16Z" level=info msg="Looking for HPAs" provider=hpa
time="2019-03-08T16:39:16Z" level=info msg="Found 0 new/updated HPA(s)" provider=hpa

**Comment by Sanjanare** [comment]
@arjunrn

**Comment by arjunrn** [comment]
@Sanjanare The only thing out of the ordinary is that the adapter stops tracking the HPA:
> time="2019-03-08T16:36:46Z" level=info msg="Removing previously scheduled metrics collector: {hazelcast dev}" provider=hpa

Can you verify that the HPA exists and is not being deleted/cleaned-up/changed?

**Comment by Sanjanare** [comment]
@arjunrn yes it is in running state...so i might have deleted to try something but later re-installed so its there ..and shows same error...

**Comment by arjunrn** [comment]
I could recreate the issue. It looks like the metrics Object does matter although it has nothing to do with how the metrics are collected. So this sections:

```yaml
target:
        apiVersion: v1
        kind: Service
        name: event-service
```
should be changed to something with `Pod` or `Ingress` in the `kind` field. It does not have to be a valid pod or ingress but it affects how the metrics are stored. So can you try that and let me know. Also just a heads up there is a `)` missing in your prometheus query.
