### ISSUE TITLE
Prometheus External Metric not working

### ISSUE THREAD

**Issue by veetow** [zalando-incubator/kube-metrics-adapter#61]
## Expected Behavior

`kube-metrics-adapter` should be able to create a metrics collector based on the example in the readme.

## Actual Behavior

`kube-metrics-adapter` logs `Failed to create new metrics collector: no plugin found for {External prometheus-query}` for my HPA.

## Steps to Reproduce the Problem

1. I'm running `kube-metrics-adapter` from the banzaicloud chart at https://github.com/banzaicloud/banzai-charts/tree/master/kube-metrics-adapter
1. I have the following HPA:
```yaml
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: selenium-node-chrome-hpa
  namespace: selenium-grid-demo
  annotations:
    "metric-config.external.prometheus-query.prometheus/selenium-grid-node-chrome-ready-count": |-
      sum(selenium_grid_node_ready{app="selenium-node-chrome",namespace="selenium-grid-demo"})
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selenium-node-chrome
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: External
    external:
      metricName: prometheus-query
      metricSelector:
        matchLabels:
          query-name: selenium-grid-node-chrome-ready-count
      targetAverageValue: 5
```
1. Verified that I'm not getting any metrics
```shell
$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
```

**Comment by mikkeloscar** [comment]
Hi, could you post the full log output of the `kube-metrics-adapter` from when you start it till you start to see those errors?

It would also be good if you could post the deployment.yaml of the final configuration. It's hard to determine the actual configuration just by looking at the chart, since there are many configuration variables.

**Comment by veetow** [comment]
Sure thing, here are the logs:
https://gist.github.com/veetow/ac91b34643f4c1678e990baa0f8f810e

Here is the deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-metrics-adapter
  labels:
    app: kube-metrics-adapter
    chart: kube-metrics-adapter-0.0.4
    release: "kube-metrics-adapter"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-metrics-adapter
      release: "kube-metrics-adapter"
  template:
    metadata:
      labels:
        app: kube-metrics-adapter
        chart: kube-metrics-adapter-0.0.4
        release: "kube-metrics-adapter"
        heritage: "Tiller"
    spec:
      serviceAccountName: kube-metrics-adapter
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
      - name: kube-metrics-adapter
        image: "banzaicloud/kube-metrics-adapter:0.1.1"
        imagePullPolicy: IfNotPresent
        args:
        - --secure-port=8443
        - --v=9
        - --prometheus-server=http://prometheus-prometheus-oper-prometheus.monitoring.svc.cluster.local:9090
        - --cert-dir=/tmp/cert
        ports:
        - containerPort: 8443
          name: https
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["all"]
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: tmp
        emptyDir: {}
```
