### ISSUE TITLE
Error: the server could not find the requested resource

### ISSUE THREAD

**Issue by alexalex89** [zalando-incubator/kube-metrics-adapter#670]
## Expected Behavior
The HPA is able to access and use external metrics provided by kube-metrics-adapter

## Actual Behavior
Error message in the HPA:
`ScalingActive   False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric internal-namespace-name/event-queue-size/&LabelSelector{MatchLabels:map[string]string{type: prometheus,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: the server could not find the requested resource (get event-queue-size.external.metrics.k8s.io)`
Also:
`"event-queue-size" (target average value):           <unknown> / 3`

The kube-metrics-adapter obviously collects the metric successfully; excerpt from the logs:
```
time="2024-02-27T09:29:00Z" level=info msg="Looking for HPAs" provider=hpa
time="2024-02-27T09:29:00Z" level=info msg="Removing previously scheduled metrics collector: {...}" provider=hpa
time="2024-02-27T09:29:00Z" level=info msg="Found 1 new/updated HPA(s)" provider=hpa
time="2024-02-27T09:29:00Z" level=info msg="Collected 1 new metric(s)" provider=hpa
time="2024-02-27T09:29:00Z" level=info msg="Collected new external metric 'internal-namespace-name/event-queue-size' (0) [type=prometheus]" provider=hpa
```

I tried looking into the metrics using `kubectl get --raw /apis/metrics.k8s.io`, but no interesting information it seems:
`{"kind":"APIGroup","apiVersion":"v1","name":"metrics.k8s.io","versions":[{"groupVersion":"metrics.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"metrics.k8s.io/v1beta1","version":"v1beta1"}}`

Executing
`kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/"`
does not work:
`Error from server (NotFound): the server could not find the requested resource`

## Steps to Reproduce the Problem

  1. Deploy kube-metrics-agent in a Namespace called kube-metrics-agent-system using a Prometheus API outside of the cluster
  2. Deploy a HPA:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    metric-config.external.event-queue-size.prometheus/interval: 60s
    metric-config.external.event-queue-size.prometheus/query: |
      event_queue_jobs_active{cluster="cluster-name", queue=~"default"}
  name: events-worker
  namespace: internal-namespace-name
spec:
  maxReplicas: 4
  metrics:
  - external:
      metric:
        name: event-queue-size
        selector:
          matchLabels:
            type: prometheus
      target:
        averageValue: "3"
        type: AverageValue
    type: External
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: events-worker
```

  3. `kubectl describe hpa -n internal-namespace-name events-worker` shows the error message from above.

## Specifications

  - Version: v0.2.0
  - Platform: Kubernetes 1.28.7
  - Subsystem: GKE

Thanks in advance!
