### ISSUE TITLE
Feature request: add Prometheus URL as annotation in HorizontalPodAutoscaler definition

### ISSUE THREAD

**Issue by edganiukov** [zalando-incubator/kube-metrics-adapter#74]
In our cluster we have several Prometheus instances. I was wondering, if it is possible to add (optional) Prometheus URL in  HorizontalPodAutoscaler definition, for example:

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
  annotations:
    metric-config.external.prometheus-query.prometheus/url: prometheus.namespace2.svc:9090 
    
# metric-config.<metricType>.<metricName>.<collectorName>/<configKey>
    # <configKey> == query-name
    metric-config.external.prometheus-query.prometheus/processed-events-per-second: |
      scalar(sum(rate(event-service_events_count{application="event-service",processed="true"}[1m])))
spec:
```

If no such annotation defined -  use the one defined as command line arguments.
